### ISSUE TITLE
Results are incomplete

### ISSUE THREAD

**Issue by dundunn** [yourselvs/RoleFilter#19]
If you use a filter the result will always be incomplete. It only shows me 20 members of a role with over 1000 users. 
Not sure if it's related to other plugins so it would be nice if someone could confirm it.

**Comment by yourselvs** [comment]
Unfortunately, this is expected. Discord's lazy-loading feature means the plugin cannot read past the first 100 members in a channel. If I look at all members of a server I could recreate it partially, but it is difficult to tell whether or not a user has access to a particular channel. It's best to use [RoleMembers](https://betterdiscord.app/plugin/RoleMembers) in that case.

This is in the [Known Issues](https://github.com/yourselvs/RoleFilter#known-issues) section of the README:
- Not always correct in channels with 100+ members
  - Due to Discord's lazy-loading, Role Filter can only look at the first 100 members in a channel
  - At the moment, a fix for this is not planned
