### ISSUE TITLE
Only online members

### ISSUE THREAD

**Issue by SaeidNH** [yourselvs/RoleFilter#8]
This shows only online members, not offline ones. Any fix ?

**Comment by yourselvs** [comment]
The plugin doesn't render anything manually right now, it just stops discord from rendering users that don't pass the filter. Thus, when a server disables viewing offline users, the current implementation does not allow offline users to show up, since discord never actually renders them.

It's possible that in the future, a fix for this is created, but it's not an easy effort and isn't planned for now.
